google_dev:
  service: GCS
  project: JDIGram
  credentials: <%= Rails.root.join("config/secrets/jdigram_gcs.json") %>
  bucket: jdigram

google:
  service: GCS
  project: JDIGram
  credentials: <%= Rails.root.join("config/secrets/jdigram_gcs.json") %>
  bucket: jdigram